### ISSUE TITLE
Z-fighting

### ISSUE THREAD

**Issue by davidthehat** [Nettakrim/Signed-Paintings#3] opened 2023-08-24 05:51 UTC
If a transparent image is used, and the frame is set to "sign" or "block", z fighting occurs between the frame material and the blocks behind the painting. This occurs when the sign in placed on the side of a block.
![image](https://github.com/Nettakrim/Signed-Paintings/assets/24359213/8c0ea6a3-174a-41ab-a471-7cd99baef8af)
![image](https://github.com/Nettakrim/Signed-Paintings/assets/24359213/b0799a5c-a637-4a32-be65-2f986fc9490c)

Z fighting always occurs when the sign is placed on the top of a block.
![image](https://github.com/Nettakrim/Signed-Paintings/assets/24359213/2602daae-3473-452b-b6de-f234a0974f1d)
![image](https://github.com/Nettakrim/Signed-Paintings/assets/24359213/6cdd79f0-3331-443a-a1ec-7bc27cad541f)

Z fighting occurs with hanging signs and glass panes.
![image](https://github.com/Nettakrim/Signed-Paintings/assets/24359213/5070c98e-72c5-4ea9-8bc0-077511d8fb14)

The ideal solution would include the ability to set the offset from the block.

**Comment by Nettakrim** [comment] 2023-08-24 10:05
the case with the transparent image and the sign on a wall is definitely avoidable, i could either extend the size of the cuboid to go through the wall, or do something cursed where only the back face is shifted forwards, creating a sort of __~~⨆~~__ shape (liquids do something similar, perhaps unintentionally)

the case where the sign is on top of a block can be considered working as intended - i want people to easily be able to make images flush with walls

hanging signs i can definitely slightly increase/decrease the cuboid depth to stop the z fighting

-----

i can add a z offset slider under the y offset one - it would probably only have a one block range

**Comment by Nettakrim** [comment] 2023-09-20 17:58
case 1 has been fixed by moving the painting a teeny amount into the block
![image](https://github.com/Nettakrim/Signed-Paintings/assets/106409257/b8f565ad-a9d0-446b-9ade-d30f6150a212)

case 2 is working as intended as explained

case 3 has been fixed the same way - this does mean the tops and bottoms of double sided hanging sign images will have a teensy bit of z fighting, however i think this is acceptable considering how cool it looks when combined with glass panes now
![image](https://github.com/Nettakrim/Signed-Paintings/assets/106409257/02c59bfb-1ce6-45c2-b15a-2d94e533ba05)

**Closed as completed** 2023-09-20 17:59 UTC
